FLASK_APP=albumy
FLASK_ENV=development
FLASK_CONFIG=development

SECRET_KEY=

MAIL_SERVER=
MAIL_USERNAME=
MAIL_PASSWORD=

DEV_MYSQL_USERNAME=
DEV_MYSQL_PASSWORD=
DEV_MYSQL_DATABASE=

PRO_MYSQL_USERNAME=
PRO_MYSQL_PASSWORD=
PRO_MYSQL_DATABASE=